version: '3.8'

services:
  apiclient:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    image: "${DOCKER_USERNAME}/aicookbook-backend:latest"
    ports:
      - "8080:8080"


volumes:
  db_data: