name: APIClient CI/CD Pipeline

on:
  push:
    branches:
        # - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/aicookbook-apiclient:latest .

      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/aicookbook-apiclient:latest

  deploy: # CD - Continuous Deployment
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Run Frontend container with Docker image
      run: docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/aicookbook-apiclient:latest